DJ_Crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('app.urls','app'), namespace='app')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path
from rest_framework_swagger.views import get_swagger_view
from .views import *

schema_view = get_swagger_view(title='API Documentation')

urlpatterns = [
    path('api/docs/', schema_view),
    path('', HtmlInicio.as_view(), name="index"),   
    path('list/', CategoryView.as_view(), name="modelo_list"),   
    path('new/', CategoryNew.as_view(), name="new"),
    path('edit/<int:pk>/', CategoryEdit.as_view(), name="edit"), 
    path('del/<int:pk>/', CategoryDel.as_view(), name="del"), 

    path('listProducto/', ProductView.as_view(), name="productos_list"),   
    path('newProducto/', ProductNew.as_view(), name="newProducto"),
    path('editProducto/<int:pk>/', ProductEdit.as_view(), name="editProducto"), 
    path('delProducto/<int:pk>/', ProductDel.as_view(), name="delProducto"),

    path('api/productos/', ProductoListView.as_view(), name='producto-list'),
]

templates/bases/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Programador Hey</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> -->

</head>
<body>
    <!-- Mensaje de Alerta -->
    <div class="alert alert-dismissible alert-warning">
        <h4 class="alert-heading">Hola!</h4>
        <p class="mb-0">Este Proyecto es parte de la prueba Tecnica para Hey Inplanet</p>
    </div>
    <!-- Barra de Navegacion -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Django Crud Hey</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!-- Urls para hacerlo de manera dinamica -->

          <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'app:modelo_list' %}">| Listar Categorias |
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app:new' %}">| Agregar Categoria | </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app:index' %}">| Volver al Menu Principal |</a>
                    </li>
                </ul>
          </div>
          
        </div>
      </nav>

      <div class="container-fluid">
        <div class="row">
          {% block content%}
          {% endblock %}
        </div>
      </div>
      
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>


</body>
</html>

templates/bases/productos.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Programador Hey</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> -->

</head>
<body>
    <!-- Mensaje de Alerta -->
    <div class="alert alert-dismissible alert-warning">
        <h4 class="alert-heading">Hola!</h4>
        <p class="mb-0">Este Proyecto es parte de la prueba Tecnica para Hey Inplanet</p>
    </div>
    <!-- Barra de Navegacion -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Django Crud Hey</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Urls para hacerlo de manera dinamica -->
          <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'app:productos_list' %}">| Listar Productos |
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app:newProducto' %}">| Agregar Productos | </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app:index' %}">| Volver al Menu Principal |</a>
                    </li>
                </ul>
          </div>
        </div>
      </nav>

      <div class="container-fluid">
        <div class="row">
          {% block content%}
          {% endblock %}
        </div>
      </div>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

</body>
</html>